.PHONY: all build

all: build

build:
	gcc main.c -o bf

hello_world: build
	echo -n "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++." | ./bf -s
